server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker_logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            jobid: jobid
            taskid: taskid
            statusid: statusid
      - labels:
          jobid:
          taskid:
          statusid:
